### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by jjasghar** [ibm-cloud-docs/iam#43]
https://cloud.ibm.com/docs-content/v1/content/4e6414a57755d2e9ec69d44dea7eb8f17841f408/iam/images/iam-diagram.svg

looks HORRIBLE.

![image](https://user-images.githubusercontent.com/810824/73003729-b7d3fc00-3dcb-11ea-8c84-d9cd82d9696e.png)

The image squishes the words down, and i attempted to resize and it didn't change.

**Comment by mekaufman** [comment]
@jjasghar What browser are you using?

**Comment by jjasghar** [comment]
Firefox 72.0.1 (64-bit) Fedora

**Comment by mekaufman** [comment]
@jjasghar Thanks for your feedback. In Chrome, it is rendering properly. I'm opening an internal issue to work with our team to see if we can address the issue being seen in Firefox.

**Comment by mekaufman** [comment]
FF 72.0.2 looks good to me even when resized. 

![image](https://user-images.githubusercontent.com/13648625/73015324-cd581e80-3de9-11ea-8aed-1e2bd32512cb.png).

Closing for now because I can't replicate the issue, but please reach out if you continue to see this issue. And, I'll do some further testing.
